apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ub4vm5hoe-nodejs 
  janus-idp.io/tekton: ub4vm5hoe-nodejs
  backstage.io/kubernetes-id: ub4vm5hoe-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ub4vm5hoe-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml