apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ub4vm5hoe-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ub4vm5hoe-nodejs 
  name: ub4vm5hoe-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ub4vm5hoe-nodejs 
